/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package JavaDevHomeWork5;

import JavaDevHomeWork5.state.MainState;
import JavaDevHomeWork5.state.State;

public class App {
    private State state;

    public App() {
        this.state = new MainState(this);
    }

    void startApp() {
        while (true) {
            state.execute();
        }
    }

    public void changeState (State state){
        this.state = state;
    }
}
